In [ ]:
# Montamos el drive en nuestra notebook para poder trabajar
#con documentos que tenemos guardados ahí
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)
# Deben ponder la ruta en que uds tienen el dataset en su Google Drive
path = 'gdrive/My Drive/Colab Notebooks/datasets/lego_sets.csv'

Mounted at /content/gdrive

In [3]:
import pandas as pd

In [4]:
lego_data = pd.read_csv(path)

# Leemos los 5 primeros datos
lego_data.head()

,set_id,name,year,theme,subtheme,themeGroup,category,pieces,minifigs,agerange_min,US_retailPrice,bricksetURL,thumbnailURL,imageURL
0,1-8,Small house set,1970,Minitalia,NaN,Vintage,Normal,67.0,NaN,NaN,NaN,https://brickset.com/sets/1-8,https://images.brickset.com/sets/small/1-8.jpg,https://images.brickset.com/sets/images/1-8.jpg
1,2-8,Medium house set,1970,Minitalia,NaN,Vintage,Normal,109.0,NaN,NaN,NaN,https://brickset.com/sets/2-8,https://images.brickset.com/sets/small/2-8.jpg,https://images.brickset.com/sets/images/2-8.jpg
2,3-6,Medium house set,1970,Minitalia,NaN,Vintage,Normal,158.0,NaN,NaN,NaN,https://brickset.com/sets/3-6,https://images.brickset.com/sets/small/3-6.jpg,https://images.brickset.com/sets/images/3-6.jpg
3,4-4,Large house set,1970,Minitalia,NaN,Vintage,Normal,233.0,NaN,NaN,NaN,https://brickset.com/sets/4-4,https://images.brickset.com/sets/small/4-4.jpg,https://images.brickset.com/sets/images/4-4.jpg
4,4-6,Mini House and Vehicles,1970,Samsonite,Model Maker,Vintage,Normal,NaN,NaN,NaN,NaN,https://brickset.com/sets/4-6,NaN,NaN

In [5]:
lego_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18457 entries, 0 to 18456
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   set_id          18457 non-null  object
 1   name            18457 non-null  object
 2   year            18457 non-null  int64
 3   theme           18457 non-null  object
 4   subtheme        14901 non-null  object
 5   themeGroup      18455 non-null  object
 6   category        18457 non-null  object
 7   pieces          14533 non-null  float64
 8   minifigs        8399 non-null   float64
 9   agerange_min    6787 non-null   float64
 10  US_retailPrice  6982 non-null   float64
 11  bricksetURL     18457 non-null  object
 12  thumbnailURL    17451 non-null  object
 13  imageURL        17451 non-null  object
dtypes: float64(4), int64(1), object(9)
memory usage: 2.0+ MB

In [6]:
# Contar los valores nulos por columna
print("Conteo de valores nulos por columna en logo_data:")
lego_data.isnull().sum().sort_values(ascending=False)

Conteo de valores nulos por columna en logo_data:

agerange_min      11670
US_retailPrice    11475
minifigs          10058
pieces             3924
subtheme           3556
imageURL           1006
thumbnailURL       1006
themeGroup            2
set_id                0
name                  0
year                  0
theme                 0
category              0
bricksetURL           0
dtype: int64

In [7]:
#Porcentaje de nulos en relacion al total
print("\nPorcentaje de valores nulos en relacion al total:")
(lego_data.isnull().mean() * 100).round(2).sort_values(ascending=False)

Porcentaje de valores nulos en relacion al total:

agerange_min      63.23
US_retailPrice    62.17
minifigs          54.49
pieces            21.26
subtheme          19.27
imageURL           5.45
thumbnailURL       5.45
themeGroup         0.01
set_id             0.00
name               0.00
year               0.00
theme              0.00
category           0.00
bricksetURL        0.00
dtype: float64

In [9]:
#Rellenar valores nulos en 'agerange_min' con la mediana

mediana_pagerange_min = lego_data['agerange_min'].median()
lego_data.fillna({'agerange_min': mediana_pagerange_min},inplace = True)

print("DataFrame después de rellenar nulos en 'Precio':")
lego_data.head()

DataFrame después de rellenar nulos en 'Precio':

,set_id,name,year,theme,subtheme,themeGroup,category,pieces,minifigs,agerange_min,US_retailPrice,bricksetURL,thumbnailURL,imageURL
0,1-8,Small house set,1970,Minitalia,NaN,Vintage,Normal,67.0,NaN,6.0,NaN,https://brickset.com/sets/1-8,https://images.brickset.com/sets/small/1-8.jpg,https://images.brickset.com/sets/images/1-8.jpg
1,2-8,Medium house set,1970,Minitalia,NaN,Vintage,Normal,109.0,NaN,6.0,NaN,https://brickset.com/sets/2-8,https://images.brickset.com/sets/small/2-8.jpg,https://images.brickset.com/sets/images/2-8.jpg
2,3-6,Medium house set,1970,Minitalia,NaN,Vintage,Normal,158.0,NaN,6.0,NaN,https://brickset.com/sets/3-6,https://images.brickset.com/sets/small/3-6.jpg,https://images.brickset.com/sets/images/3-6.jpg
3,4-4,Large house set,1970,Minitalia,NaN,Vintage,Normal,233.0,NaN,6.0,NaN,https://brickset.com/sets/4-4,https://images.brickset.com/sets/small/4-4.jpg,https://images.brickset.com/sets/images/4-4.jpg
4,4-6,Mini House and Vehicles,1970,Samsonite,Model Maker,Vintage,Normal,NaN,NaN,6.0,NaN,https://brickset.com/sets/4-6,NaN,NaN

In [12]:
#Rellenar valores nulos en 'US_retailPrice' con la mediana

mediana_US_retailPrice = lego_data['US_retailPrice'].median()
lego_data.fillna({'US_retailPrice': mediana_pagerange_min},inplace = True)

print("DataFrame después de rellenar nulos en 'Precio':")
lego_data.head()

DataFrame después de rellenar nulos en 'Precio':

,set_id,name,year,theme,subtheme,themeGroup,category,pieces,minifigs,agerange_min,US_retailPrice,bricksetURL,thumbnailURL,imageURL
0,1-8,Small house set,1970,Minitalia,NaN,Vintage,Normal,67.0,NaN,6.0,6.0,https://brickset.com/sets/1-8,https://images.brickset.com/sets/small/1-8.jpg,https://images.brickset.com/sets/images/1-8.jpg
1,2-8,Medium house set,1970,Minitalia,NaN,Vintage,Normal,109.0,NaN,6.0,6.0,https://brickset.com/sets/2-8,https://images.brickset.com/sets/small/2-8.jpg,https://images.brickset.com/sets/images/2-8.jpg
2,3-6,Medium house set,1970,Minitalia,NaN,Vintage,Normal,158.0,NaN,6.0,6.0,https://brickset.com/sets/3-6,https://images.brickset.com/sets/small/3-6.jpg,https://images.brickset.com/sets/images/3-6.jpg
3,4-4,Large house set,1970,Minitalia,NaN,Vintage,Normal,233.0,NaN,6.0,6.0,https://brickset.com/sets/4-4,https://images.brickset.com/sets/small/4-4.jpg,https://images.brickset.com/sets/images/4-4.jpg
4,4-6,Mini House and Vehicles,1970,Samsonite,Model Maker,Vintage,Normal,NaN,NaN,6.0,6.0,https://brickset.com/sets/4-6,NaN,NaN

In [16]:
#Rellenar valores nulos en 'minifigs' con la mediana

mediana_minifigs = lego_data['minifigs'].median()
lego_data.fillna({'minifigs': mediana_pagerange_min},inplace = True)

print("DataFrame después de rellenar nulos en 'Precio':")
lego_data.head()

DataFrame después de rellenar nulos en 'Precio':

,set_id,name,year,theme,subtheme,themeGroup,category,pieces,minifigs,agerange_min,US_retailPrice,bricksetURL,thumbnailURL,imageURL
0,1-8,Small house set,1970,Minitalia,NaN,Vintage,Normal,67.0,6.0,6.0,6.0,https://brickset.com/sets/1-8,https://images.brickset.com/sets/small/1-8.jpg,https://images.brickset.com/sets/images/1-8.jpg
1,2-8,Medium house set,1970,Minitalia,NaN,Vintage,Normal,109.0,6.0,6.0,6.0,https://brickset.com/sets/2-8,https://images.brickset.com/sets/small/2-8.jpg,https://images.brickset.com/sets/images/2-8.jpg
2,3-6,Medium house set,1970,Minitalia,NaN,Vintage,Normal,158.0,6.0,6.0,6.0,https://brickset.com/sets/3-6,https://images.brickset.com/sets/small/3-6.jpg,https://images.brickset.com/sets/images/3-6.jpg
3,4-4,Large house set,1970,Minitalia,NaN,Vintage,Normal,233.0,6.0,6.0,6.0,https://brickset.com/sets/4-4,https://images.brickset.com/sets/small/4-4.jpg,https://images.brickset.com/sets/images/4-4.jpg
4,4-6,Mini House and Vehicles,1970,Samsonite,Model Maker,Vintage,Normal,NaN,6.0,6.0,6.0,https://brickset.com/sets/4-6,NaN,NaN

In [18]:
#Rellenar valores nulos en 'pieces' con la mediana

mediana_pieces = lego_data['pieces'].median()
lego_data.fillna({'pieces': mediana_pagerange_min},inplace = True)

print("DataFrame después de rellenar nulos en 'Precio':")
lego_data.head()

DataFrame después de rellenar nulos en 'Precio':

,set_id,name,year,theme,subtheme,themeGroup,category,pieces,minifigs,agerange_min,US_retailPrice,bricksetURL,thumbnailURL,imageURL
0,1-8,Small house set,1970,Minitalia,NaN,Vintage,Normal,67.0,6.0,6.0,6.0,https://brickset.com/sets/1-8,https://images.brickset.com/sets/small/1-8.jpg,https://images.brickset.com/sets/images/1-8.jpg
1,2-8,Medium house set,1970,Minitalia,NaN,Vintage,Normal,109.0,6.0,6.0,6.0,https://brickset.com/sets/2-8,https://images.brickset.com/sets/small/2-8.jpg,https://images.brickset.com/sets/images/2-8.jpg
2,3-6,Medium house set,1970,Minitalia,NaN,Vintage,Normal,158.0,6.0,6.0,6.0,https://brickset.com/sets/3-6,https://images.brickset.com/sets/small/3-6.jpg,https://images.brickset.com/sets/images/3-6.jpg
3,4-4,Large house set,1970,Minitalia,NaN,Vintage,Normal,233.0,6.0,6.0,6.0,https://brickset.com/sets/4-4,https://images.brickset.com/sets/small/4-4.jpg,https://images.brickset.com/sets/images/4-4.jpg
4,4-6,Mini House and Vehicles,1970,Samsonite,Model Maker,Vintage,Normal,6.0,6.0,6.0,6.0,https://brickset.com/sets/4-6,NaN,NaN

In [20]:
#Rellenar valores nulos en 'subtheme' con 'Desconocido'
lego_data.fillna({'subtheme' : "Desconocido"}, inplace = True)
lego_data.head()

,set_id,name,year,theme,subtheme,themeGroup,category,pieces,minifigs,agerange_min,US_retailPrice,bricksetURL,thumbnailURL,imageURL
0,1-8,Small house set,1970,Minitalia,Desconocido,Vintage,Normal,67.0,6.0,6.0,6.0,https://brickset.com/sets/1-8,https://images.brickset.com/sets/small/1-8.jpg,https://images.brickset.com/sets/images/1-8.jpg
1,2-8,Medium house set,1970,Minitalia,Desconocido,Vintage,Normal,109.0,6.0,6.0,6.0,https://brickset.com/sets/2-8,https://images.brickset.com/sets/small/2-8.jpg,https://images.brickset.com/sets/images/2-8.jpg
2,3-6,Medium house set,1970,Minitalia,Desconocido,Vintage,Normal,158.0,6.0,6.0,6.0,https://brickset.com/sets/3-6,https://images.brickset.com/sets/small/3-6.jpg,https://images.brickset.com/sets/images/3-6.jpg
3,4-4,Large house set,1970,Minitalia,Desconocido,Vintage,Normal,233.0,6.0,6.0,6.0,https://brickset.com/sets/4-4,https://images.brickset.com/sets/small/4-4.jpg,https://images.brickset.com/sets/images/4-4.jpg
4,4-6,Mini House and Vehicles,1970,Samsonite,Model Maker,Vintage,Normal,6.0,6.0,6.0,6.0,https://brickset.com/sets/4-6,NaN,NaN

In [22]:
#Rellenar valores nulos en 'imageURL' con 'Desconocido'
lego_data.fillna({'imageURL' : "Desconocido"}, inplace = True)
lego_data.head()

,set_id,name,year,theme,subtheme,themeGroup,category,pieces,minifigs,agerange_min,US_retailPrice,bricksetURL,thumbnailURL,imageURL
0,1-8,Small house set,1970,Minitalia,Desconocido,Vintage,Normal,67.0,6.0,6.0,6.0,https://brickset.com/sets/1-8,https://images.brickset.com/sets/small/1-8.jpg,https://images.brickset.com/sets/images/1-8.jpg
1,2-8,Medium house set,1970,Minitalia,Desconocido,Vintage,Normal,109.0,6.0,6.0,6.0,https://brickset.com/sets/2-8,https://images.brickset.com/sets/small/2-8.jpg,https://images.brickset.com/sets/images/2-8.jpg
2,3-6,Medium house set,1970,Minitalia,Desconocido,Vintage,Normal,158.0,6.0,6.0,6.0,https://brickset.com/sets/3-6,https://images.brickset.com/sets/small/3-6.jpg,https://images.brickset.com/sets/images/3-6.jpg
3,4-4,Large house set,1970,Minitalia,Desconocido,Vintage,Normal,233.0,6.0,6.0,6.0,https://brickset.com/sets/4-4,https://images.brickset.com/sets/small/4-4.jpg,https://images.brickset.com/sets/images/4-4.jpg
4,4-6,Mini House and Vehicles,1970,Samsonite,Model Maker,Vintage,Normal,6.0,6.0,6.0,6.0,https://brickset.com/sets/4-6,NaN,Desconocido

In [24]:
#Rellenar valores nulos en 'thumbnailURL' con 'Desconocido'
lego_data.fillna({'thumbnailURL' : "Desconocido"}, inplace = True)
lego_data.head()

,set_id,name,year,theme,subtheme,themeGroup,category,pieces,minifigs,agerange_min,US_retailPrice,bricksetURL,thumbnailURL,imageURL
0,1-8,Small house set,1970,Minitalia,Desconocido,Vintage,Normal,67.0,6.0,6.0,6.0,https://brickset.com/sets/1-8,https://images.brickset.com/sets/small/1-8.jpg,https://images.brickset.com/sets/images/1-8.jpg
1,2-8,Medium house set,1970,Minitalia,Desconocido,Vintage,Normal,109.0,6.0,6.0,6.0,https://brickset.com/sets/2-8,https://images.brickset.com/sets/small/2-8.jpg,https://images.brickset.com/sets/images/2-8.jpg
2,3-6,Medium house set,1970,Minitalia,Desconocido,Vintage,Normal,158.0,6.0,6.0,6.0,https://brickset.com/sets/3-6,https://images.brickset.com/sets/small/3-6.jpg,https://images.brickset.com/sets/images/3-6.jpg
3,4-4,Large house set,1970,Minitalia,Desconocido,Vintage,Normal,233.0,6.0,6.0,6.0,https://brickset.com/sets/4-4,https://images.brickset.com/sets/small/4-4.jpg,https://images.brickset.com/sets/images/4-4.jpg
4,4-6,Mini House and Vehicles,1970,Samsonite,Model Maker,Vintage,Normal,6.0,6.0,6.0,6.0,https://brickset.com/sets/4-6,Desconocido,Desconocido

In [26]:
#Rellenar valores nulos en 'themeGroup' con 'Desconocido'
lego_data.fillna({'themeGroup' : "Desconocido"}, inplace = True)
lego_data.head()

,set_id,name,year,theme,subtheme,themeGroup,category,pieces,minifigs,agerange_min,US_retailPrice,bricksetURL,thumbnailURL,imageURL
0,1-8,Small house set,1970,Minitalia,Desconocido,Vintage,Normal,67.0,6.0,6.0,6.0,https://brickset.com/sets/1-8,https://images.brickset.com/sets/small/1-8.jpg,https://images.brickset.com/sets/images/1-8.jpg
1,2-8,Medium house set,1970,Minitalia,Desconocido,Vintage,Normal,109.0,6.0,6.0,6.0,https://brickset.com/sets/2-8,https://images.brickset.com/sets/small/2-8.jpg,https://images.brickset.com/sets/images/2-8.jpg
2,3-6,Medium house set,1970,Minitalia,Desconocido,Vintage,Normal,158.0,6.0,6.0,6.0,https://brickset.com/sets/3-6,https://images.brickset.com/sets/small/3-6.jpg,https://images.brickset.com/sets/images/3-6.jpg
3,4-4,Large house set,1970,Minitalia,Desconocido,Vintage,Normal,233.0,6.0,6.0,6.0,https://brickset.com/sets/4-4,https://images.brickset.com/sets/small/4-4.jpg,https://images.brickset.com/sets/images/4-4.jpg
4,4-6,Mini House and Vehicles,1970,Samsonite,Model Maker,Vintage,Normal,6.0,6.0,6.0,6.0,https://brickset.com/sets/4-6,Desconocido,Desconocido

In [28]:
lego_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18457 entries, 0 to 18456
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   set_id          18457 non-null  object
 1   name            18457 non-null  object
 2   year            18457 non-null  int64
 3   theme           18457 non-null  object
 4   subtheme        18457 non-null  object
 5   themeGroup      18457 non-null  object
 6   category        18457 non-null  object
 7   pieces          18457 non-null  float64
 8   minifigs        18457 non-null  float64
 9   agerange_min    18457 non-null  float64
 10  US_retailPrice  18457 non-null  float64
 11  bricksetURL     18457 non-null  object
 12  thumbnailURL    18457 non-null  object
 13  imageURL        18457 non-null  object
dtypes: float64(4), int64(1), object(9)
memory usage: 2.0+ MB

In [27]:
# Contar los valores nulos por columna
print("Conteo de valores nulos por columna en logo_data:")
lego_data.isnull().sum().sort_values(ascending=False)

Conteo de valores nulos por columna en logo_data:

set_id            0
name              0
year              0
theme             0
subtheme          0
themeGroup        0
category          0
pieces            0
minifigs          0
agerange_min      0
US_retailPrice    0
bricksetURL       0
thumbnailURL      0
imageURL          0
dtype: int64