In [30]:
import pandas as pd
import numpy as np

# conjunto de datos
data = {
    "Producto": ["Laptop", "Teclado", "Mouse", "Monitor", "Impresora", np.nan, "Webcam", "Auriculares", "Altavoces", "Router",
                 "Teclado", "Mouse", np.nan, "Monitor", "Laptop", "Impresora", "Webcam", np.nan, "Auriculares", "Altavoces"],
    "Precio": [1200, 75, 25, 300, np.nan, 50, 60, 150, np.nan, 80,
               70, 20, 350, 280, np.nan, 45, 55, 160, 90, np.nan],
    "Stock": [50, 150, 200, 30, 10, 80, np.nan, 120, 40, 70,
              130, 180, 25, np.nan, 15, 90, 65, 110, np.nan, 55],
    "Categoria": ["Electrónica", "Periféricos", "Periféricos", "Electrónica", "Electrónica", "Periféricos",
                  "Periféricos", "Electrónica", "Electrónica", "Redes",
                  "Periféricos", "Periféricos", "Electrónica", "Electrónica", "Electrónica", "Periféricos",
                  "Periféricos", "Electrónica", "Electrónica", "Redes"],
    "Valoracion": [4.5, 4.0, 4.2, 4.8, 3.5, 4.1, 3.9, np.nan, 4.6, 4.3,
                   3.8, 4.0, np.nan, 4.7, 4.4, 3.6, 3.7, 4.5, 4.1, np.nan]
}

df = pd.DataFrame(data)
df.head(10)

      Producto  Precio  Stock    Categoria  Valoracion
0       Laptop  1200.0   50.0  Electrónica         4.5
1      Teclado    75.0  150.0  Periféricos         4.0
2        Mouse    25.0  200.0  Periféricos         4.2
3      Monitor   300.0   30.0  Electrónica         4.8
4    Impresora     NaN   10.0  Electrónica         3.5
5          NaN    50.0   80.0  Periféricos         4.1
6       Webcam    60.0    NaN  Periféricos         3.9
7  Auriculares   150.0  120.0  Electrónica         NaN
8    Altavoces     NaN   40.0  Electrónica         4.6
9       Router    80.0   70.0        Redes         4.3

Hacer un conteo inicial de nulos.

In [31]:
# Contar los valores nulos por columna
print("Conteo de valores nulos por columna en df:")
df.isnull().sum().sort_values(ascending=False)

Conteo de valores nulos por columna en df:

Precio        4
Producto      3
Stock         3
Valoracion    3
Categoria     0
dtype: int64

In [32]:
#Porcentaje de nulos en relacion al total
print("\nPorcentaje de valores nulos en relacion al total:")
(df.isnull().mean() * 100).round(2)

Porcentaje de valores nulos en relacion al total:

Producto      15.0
Precio        20.0
Stock         15.0
Categoria      0.0
Valoracion    15.0
dtype: float64

Aplicar al menos 2 métodos de imputación distintos

In [33]:
# Método 1: Rellenar valores nulos en 'Producto' con 'Desconocido'
df.fillna({'Producto' : "Desconocido"}, inplace = True)
df.head()

    Producto  Precio  Stock    Categoria  Valoracion
0     Laptop  1200.0   50.0  Electrónica         4.5
1    Teclado    75.0  150.0  Periféricos         4.0
2      Mouse    25.0  200.0  Periféricos         4.2
3    Monitor   300.0   30.0  Electrónica         4.8
4  Impresora     NaN   10.0  Electrónica         3.5

In [34]:
# Método 2: Rellenar valores nulos en 'Precio' con la mediana

mediana_precio = df['Precio'].median()
df.fillna({'Precio': mediana_precio},inplace = True)

print("DataFrame después de rellenar nulos en 'Precio':")
df.head()

DataFrame después de rellenar nulos en 'Precio':

    Producto  Precio  Stock    Categoria  Valoracion
0     Laptop  1200.0   50.0  Electrónica         4.5
1    Teclado    75.0  150.0  Periféricos         4.0
2      Mouse    25.0  200.0  Periféricos         4.2
3    Monitor   300.0   30.0  Electrónica         4.8
4  Impresora    77.5   10.0  Electrónica         3.5

In [35]:
# Método 3: Rellenar valores nulos en 'Stock' con la media (promedio)
media_stock = df['Stock'].mean()
df.fillna({'Stock': media_stock},inplace = True)

print("DataFrame después de rellenar nulos en 'Stock':")
df.head()

DataFrame después de rellenar nulos en 'Stock':

    Producto  Precio  Stock    Categoria  Valoracion
0     Laptop  1200.0   50.0  Electrónica         4.5
1    Teclado    75.0  150.0  Periféricos         4.0
2      Mouse    25.0  200.0  Periféricos         4.2
3    Monitor   300.0   30.0  Electrónica         4.8
4  Impresora    77.5   10.0  Electrónica         3.5

In [36]:
# Método 4: Rellenar valores nulos en 'Valoracion' con la moda
moda_valoracion = df['Valoracion'].mode()[0]
df.fillna({'Valoracion': moda_valoracion},inplace = True)

print("DataFrame después de rellenar nulos en 'Valoracion':")
df.head()

DataFrame después de rellenar nulos en 'Valoracion':

    Producto  Precio  Stock    Categoria  Valoracion
0     Laptop  1200.0   50.0  Electrónica         4.5
1    Teclado    75.0  150.0  Periféricos         4.0
2      Mouse    25.0  200.0  Periféricos         4.2
3    Monitor   300.0   30.0  Electrónica         4.8
4  Impresora    77.5   10.0  Electrónica         3.5

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Producto    20 non-null     object
 1   Precio      20 non-null     float64
 2   Stock       20 non-null     float64
 3   Categoria   20 non-null     object
 4   Valoracion  20 non-null     float64
dtypes: float64(3), object(2)
memory usage: 932.0+ bytes

In [38]:
# Contar los valores nulos por columna
print("Conteo de valores nulos por columna en df:")
df.isnull().sum().sort_values(ascending=False)

Conteo de valores nulos por columna en df:

Producto      0
Precio        0
Stock         0
Categoria     0
Valoracion    0
dtype: int64